#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for creating a list of directories from Makefiles $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: nfsdtop/Mk/make_directories 2020-03-04 16:01:40 -0800 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: make_directories PATH ...
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Utility pathnames
#
: ${MKDIR:=mkdir}
: ${TOUCH:=touch}

############################################################ FUNCTIONS

eval2()
{
	echo "$*"
	eval "$@"
}

############################################################ MAIN

#
# Check for sentinel
#
[ -e .dirs_created ] && exit $SUCCESS

#
# Validate number of arguments
#
if [ $# -lt 1 ]; then
	$TOUCH .dirs_created
	exit
fi

#
# Create directory path(s)
#
set -e
while [ $# -ge 1 ]; do
	eval2 $MKDIR -p "$1"
	shift 1
done

#
# Create sentinel
#
$TOUCH .dirs_created

################################################################################
# END
################################################################################
