#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for getting the package name from a BSD-style packing-list $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: nfsdtop/Mk/pkgname 2020-05-14 17:55:22 -0700 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: pkgname PLIST
#
############################################################ INCLUDES

progdir="${0%/*}"
. "$progdir/manifest.subr" || exit

############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# Utility pathnames
#
: ${AWK:=awk}

############################################################ MAIN

#
# Validate number of arguments
#
[ $# -gt 0 ] || exit $SUCCESS

#
# Get the package name
#
FILE="$1"
case "$FILE" in
*PLIST|*CONTENTS)
	$AWK '
		sub(/^@name[[:space:]]+/, "") { print; exit found++ }
		END { exit !found }
	' "$FILE"
	;;
*) # MANIFEST
	manifest_read -r "(name|version)" "$FILE" || exit
	echo "$name${version:+-}$version"
esac

################################################################################
# END
################################################################################
