#!/bin/sh
# -*- tab-width: 4 -*- ;; Emacs
# vi: set noexpandtab  :: Vi/ViM
############################################################ IDENT(1)
#
# $Title: Script for getting the package tag name from an RPM SPEC-file $
# $Copyright: 1999-2017 Devin Teske. All rights reserved. $
# $FrauBSD: nfsdtop/Mk/rpmtagname 2020-03-04 16:01:40 -0800 freebsdfrau $
#
############################################################ INFORMATION
#
# Usage: rpmtagname SPECFILE
#
############################################################ GLOBALS

#
# Global exit status
#
SUCCESS=0
FAILURE=1

#
# OS Glue
#
: ${UNAME_s:=$( uname -s )}

#
# Utility pathnames
#
: ${AWK:=awk}

############################################################ FUNCTIONS

if ! type realpath > /dev/null 2>&1; then
case "$UNAME_s" in
Darwin)
realpath()
{
	perl -le 'use Cwd; print Cwd::abs_path(@ARGV)' -- "$@"
}
;;
*)
realpath()
{
	readlink -f "$@"
}
esac
fi

############################################################ MAIN

#
# Validate number of arguments
#
[ $# -gt 0 ] || exit $SUCCESS

#
# Build the tag prefix
#
PWD=$( realpath "$PWD" )
if [ "$PKGCENTER" ]; then
	PKGCENTER=$( realpath "$PKGCENTER" )
else
	PKGCENTER="$PWD"
	while [ "$PKGCENTER" ]; do
		[ -e "$PKGCENTER/Mk/pkgcenter_readconf" ] && break
		case "$PKGCENTER" in
		*/*) PKGCENTER="${PKGCENTER%/*}" ;;
		  *) PKGCENTER=
		esac
	done
fi
TAGPREFIX="${PWD#${PKGCENTER%/*}/}" # Remove everything leading up to pkgcenter
TAGPREFIX="${TAGPREFIX%/*}"

#
# Get the RPM name from the SPECFILE and return suitable tag name
#
FILE="$1"
$AWK -v prefix="${TAGPREFIX:+$TAGPREFIX/}" '
	BEGIN { gsub("/", "-", prefix) }
	sub(/^[[:space:]]*[Nn][Aa][Mm][Ee]:[[:space:]]*/, "") {
		gsub(/[^[:alnum:]]!&+,=_-]/, "_")
		print prefix $0
	}
' "$FILE"

################################################################################
# END
################################################################################
